[project]
name = "my_package"
version = "0.1.0"
description = "Minimal MLOps package for demo"
authors = [{ name = "Ghady Nehme" }]
requires-python = ">=3.9"

dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
]

[tool.uv.dev-dependencies]
jupyter = "*"